version: '3.8'

services:
  postgres:
    image: postgres:16-alpine       # alpine = лёгкий образ без лишнего
    container_name: registration_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: registration_db
    ports:
      - '5434:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
